<?php

namespace ManageUser\Controller;

use App\Controller\AppController as BaseController;

use Cake\Event\EventInterface;

class AppController extends BaseController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function beforeRender(EventInterface $event)
    {
        return parent::beforeRender($event); // TODO: Change the autogenerated stub
    }
}
